### ISSUE TITLE
Replace jackan

### ISSUE THREAD

**Issue by franck-boucher** [ozwillo/ozwillo-dc-exporter#47]

**Comment by bobeal** [comment]
This library may be a good choice for the HTTP client part : http://square.github.io/okhttp/.

**Comment by tbroyer** [comment]
OkHttp indeed **is** a good choice (I'm biased: I work with the developers on various other projects; though from a more objective point of view, OkHttp is the "native" implementation behind `java.net.HttpURLConnection` in Android since 4.4 (KitKat) — [_source_](https://twitter.com/JakeWharton/status/482563299511250944)).

And for higher-level APIs, have a look at https://square.github.io/retrofit/
