### ISSUE TITLE
Duplicate format field in exported resources

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-dc-exporter#82]
* See for instance : https://opendata.ozwillo-preprod.eu/dataset/codes-naf/resource/2833fcb6-21e7-40e7-9499-adf1573ee5b6

![screen shot 2017-04-29 at 10 07 48](https://cloud.githubusercontent.com/assets/175382/25554038/d067bc5a-2cc3-11e7-95f2-7f5533f77d5f.png)

**Comment by geraldgole** [comment]
This is not a bug from DcExporter. 

`format` parameter is necessary during resource creation to indicate which kind of resource it is.

The problem comes from CKAN UI that does not blacklist `format` field while displaying resource information.

This can be reproducible 

- with a simple POST request (on https://opendata.ozwillo-preprod.eu/api/3/action/resource_create) with the following body :
```
{
  "package_id": "737fe573-ab63-4318-a18a-13c71cec55c9",
  "url": "xxxxx",
  "name": "With Restlet9",
  "format": "JSON"
}
```
- or simply by editing resource format in CKAN UI

**Comment by bobeal** [comment]
Weird. Did you find something about this problem in the CKAN issues ?

The format field is optional (http://docs.ckan.org/en/ckan-2.7.3/api/#module-ckan.logic.action.create), maybe we could simply let CKAN guess it ?

**Comment by geraldgole** [comment]
I haven't seen any issue about this.

We found 2 examples of public CKAN where bug is present and not : 

- https://data.nsw.gov.au/data/dataset/sydney-region-dwellings/resource/e3a50156-78d0-44ae-bd78-035470cec781

- https://catalog.data.gov/dataset/college-scorecard/resource/2a7f670e-0799-436a-9394-df0a9b3ba7c5

`created` field has the same problem

You can have a look to https://github.com/ckan/ckan/blob/master/ckan/templates/package/resource_read.html#L163

First 4 capitalized fields are a combination of object internal fields.
And then filtered internal fields are displayed.
Method that filters fields is here : https://github.com/ckan/ckan/blob/master/ckan/lib/helpers.py#L2154

**Comment by bobeal** [comment]
More of a CKAN problem finally. Will be dealt with on the other side.
